/// Specialized dimension table for defining ordered steps in a financial waterfall chart.
table WaterfallSteps
	isHidden
	lineageTag: a748cde3-1ef7-4c30-9a04-4b5be7e36085

	/// Returns a signed value for each waterfall step, based on business logic for revenue and costs.
	/// Used to visualize incremental changes across steps in the financial waterfall analysis.
	measure WaterfallValue = ```
			
			SWITCH(
			    SELECTEDVALUE(WaterfallSteps[Step]),
			    "Revenue", [Revenue],
			    "COGS", -[COGS],
			 //   ,"Gross Margin", [Base Gross Margin]
			    "Tariff Cost", -[Tariff Cost]
			)
			
			```
		formatString: #,0
		isHidden
		displayFolder: Measures
		lineageTag: 5485c3bb-157b-421d-8a7f-eaf916d7c01e

	/// Label for each step in the waterfall process; controls display and selection behavior.
	column Step
		isHidden
		lineageTag: b4710f97-790f-4ade-a4f8-dde146572e34
		summarizeBy: none
		isNameInferred
		sourceColumn: [Step]
		sortByColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	/// Determines the display sequence of steps in the waterfall visualization.
	column SortOrder
		isHidden
		formatString: 0
		lineageTag: 8bbaf351-5608-41bf-82f0-a4d694a84f48
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SortOrder]

		annotation SummarizationSetBy = Automatic

	/// Loads hardcoded step definitions used for waterfall sequencing and logic mapping.
	partition WaterfallSteps = calculated
		mode: import
		source = ```
				DATATABLE(
				    "Step", STRING,
				    "SortOrder", INTEGER,
				    {
				        {"Revenue", 1},
				        {"COGS", 2},
				        {"Gross Margin", 3},
				        {"Tariff Cost", 4},
				        {"Tariff Gross Margin", 5}
				    }
				)
				
				```

	annotation PBI_Id = 6ff0012ce18e43a0a4921d603dff9bb2

